In [1]:
import pandas as pd
import numpy as np

from sklearn.cluster import KMeans

In [2]:
df = pd.read_csv("quora_cleaned_sample.csv")

print(df.shape)
df.head()

(10001, 3)

,doc_id,original_text,cleaned_text
0,1,What is the step by step guide to invest in sh...,step step guide invest share market india
1,2,What is the step by step guide to invest in sh...,step step guide invest share market
2,3,What is the story of Kohinoor (Koh-i-Noor) Dia...,story kohinoor diamond
3,4,What would happen if the Indian government sto...,would happen indian government stole kohinoor ...
4,5,How can I increase the speed of my internet co...,increase speed internet connection using vpn

In [3]:
import os

print(os.listdir())

['.anaconda', '.android', '.aws', '.azure', '.bash_history', '.cache', '.conda', '.config', '.continuum', '.copilot', '.docker', '.emulator_console_auth_token', '.firebaserc', '.gitconfig', '.gitignore', '.gradle', '.ipynb_checkpoints', '.ipython', '.ir_datasets', '.jdks', '.jupyter', '.lesshst', '.m2', '.ms-ad', '.nbi', '.node_repl_history', '.nuget', '.oracle_jre_usage', '.packettracer', '.VirtualBox', '.vscode', '.vscode-shared', '2021.8.3', '3D Objects', '6.2.0', 'anaconda3', 'anaconda_projects', 'app', 'AppData', 'Application Data', 'build.gradle.kts', 'Contacts', 'Control Panel - Shortcut.lnk', 'Cookies', 'Desktop', 'Documents', 'Document_Clustering_Service.ipynb', 'Downloads', 'Favorites', 'firebase.json', 'firestore.indexes.json', 'firestore.rules', 'flutter', 'ghazal.ipynb', 'gradle', 'gradle.properties', 'gradlew', 'gradlew.bat', 'IdeaProjects', 'IntelGraphicsProfiles', 'Links', 'Local Settings', 'local.properties', 'minesweeper.jsx', 'model_cache', 'Music', 'My Documents', 'mytest', 'NetHood', 'nltk)', 'npm-cache', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'pglite-debug.log', 'PhpstormProjects', 'Pictures', 'Postman', 'PrintHood', 'project', 'quora_cleaned_sample.csv', 'quora_embeddings.npy', 'Recent', 'sample_embeddings.npy', 'Saved Games', 'Searches', 'SendTo', 'settings.gradle.kts', 'source', 'Start Menu', 'StudioProjects', 'Templates', 'test', 'test_app', 'untitled', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Videos', 'VirtualBox VMs', 'vscode-remote-wsl']

In [4]:
import numpy as np

embeddings = np.load("quora_embeddings.npy")

print(embeddings.shape)

(10001, 384)

In [5]:
from sklearn.cluster import KMeans

k = 10

kmeans = KMeans(
    n_clusters=k,
    random_state=42,
    n_init=10
)

clusters = kmeans.fit_predict(embeddings)

print(clusters[:20])

[5 7 9 5 4 4 8 2 3 3 6 6 7 4 6 6 9 9 2 4]

In [6]:
df["cluster"] = clusters

df.head()

,doc_id,original_text,cleaned_text,cluster
0,1,What is the step by step guide to invest in sh...,step step guide invest share market india,5
1,2,What is the step by step guide to invest in sh...,step step guide invest share market,7
2,3,What is the story of Kohinoor (Koh-i-Noor) Dia...,story kohinoor diamond,9
3,4,What would happen if the Indian government sto...,would happen indian government stole kohinoor ...,5
4,5,How can I increase the speed of my internet co...,increase speed internet connection using vpn,4

In [7]:
for i in range(10):
    print(f"\n===== Cluster {i} =====")

    docs = df[df["cluster"] == i]["cleaned_text"].head(5)

    for doc in docs:
        print("-", doc)

===== Cluster 0 =====
- first sexual experience like
- first sexual experience
- girls want friends guy reject
- guys feel rejecting girl
- causing someone jealous

===== Cluster 1 =====
- make physics easy learn
- make physics easy learn
- laws change status student visa green card us compare immigration laws canada
- would trump presidency mean current international master students f1 visa
- trump presidency affect students presently us planning study us

===== Cluster 2 =====
- find remainder math 24 divided
- motorola company hack charter motorolla dcx3400
- things technicians tell durability reliability laptops components
- rockets look white
- rockets boosters painted white

===== Cluster 3 =====
- one dissolve water quikly sugar salt methane carbon di oxide
- fish would survive salt water
- special cares someone nose gets stuffy night
- keep nose getting stuffy night
- squats make legs thicker

===== Cluster 4 =====
- increase speed internet connection using vpn
- internet speed increased hacking dns
- keeps childern active far phone video games
- hack motorola dcx3400 free internet
- read find youtube comments

===== Cluster 5 =====
- step step guide invest share market india
- would happen indian government stole kohinoor diamond back
- difficult get rsi
- bjp government strip muslims christians indian citizenship put boats like rohingya burma
- india apply model deport illegal bangladeshis

===== Cluster 6 =====
- astrology capricorn sun cap moon cap rising say
- triple capricorn sun moon ascendant capricorn say
- good geologist
- great geologist
- method find separation slits using fresnel biprism

===== Cluster 7 =====
- step step guide invest share market
- buy tiago
- best digital marketing institution banglore
- best digital marketing institute pune
- best way make money online

===== Cluster 8 =====
- mentally lonely solve
- manipulation mean
- manipulation means
- one thing despite knowing better
- nd always sad

===== Cluster 9 =====
- story kohinoor diamond
- use シ instead し
- use instead
- see youtube comments
- one thing would like better

In [8]:
print(df["cluster"].value_counts())

cluster
6    1458
1    1264
2    1186
9    1084
3     921
4     913
0     842
7     841
5     750
8     742
Name: count, dtype: int64

In [9]:
for i in range(10):
    print(f"\n===== Cluster {i} =====")

    sample = df[df["cluster"] == i]["cleaned_text"].head(5)

    for text in sample:
        print("-", text)

===== Cluster 0 =====
- first sexual experience like
- first sexual experience
- girls want friends guy reject
- guys feel rejecting girl
- causing someone jealous

===== Cluster 1 =====
- make physics easy learn
- make physics easy learn
- laws change status student visa green card us compare immigration laws canada
- would trump presidency mean current international master students f1 visa
- trump presidency affect students presently us planning study us

===== Cluster 2 =====
- find remainder math 24 divided
- motorola company hack charter motorolla dcx3400
- things technicians tell durability reliability laptops components
- rockets look white
- rockets boosters painted white

===== Cluster 3 =====
- one dissolve water quikly sugar salt methane carbon di oxide
- fish would survive salt water
- special cares someone nose gets stuffy night
- keep nose getting stuffy night
- squats make legs thicker

===== Cluster 4 =====
- increase speed internet connection using vpn
- internet speed increased hacking dns
- keeps childern active far phone video games
- hack motorola dcx3400 free internet
- read find youtube comments

===== Cluster 5 =====
- step step guide invest share market india
- would happen indian government stole kohinoor diamond back
- difficult get rsi
- bjp government strip muslims christians indian citizenship put boats like rohingya burma
- india apply model deport illegal bangladeshis

===== Cluster 6 =====
- astrology capricorn sun cap moon cap rising say
- triple capricorn sun moon ascendant capricorn say
- good geologist
- great geologist
- method find separation slits using fresnel biprism

===== Cluster 7 =====
- step step guide invest share market
- buy tiago
- best digital marketing institution banglore
- best digital marketing institute pune
- best way make money online

===== Cluster 8 =====
- mentally lonely solve
- manipulation mean
- manipulation means
- one thing despite knowing better
- nd always sad

===== Cluster 9 =====
- story kohinoor diamond
- use シ instead し
- use instead
- see youtube comments
- one thing would like better

In [10]:
df.to_csv("clustered_documents.csv", index=False)