In [3]:
import pandas as pd

df = pd.read_csv(r"C:\quora_cleaned_sample.csv")

df.head()

,doc_id,original_text,cleaned_text
0,1,What is the step by step guide to invest in sh...,step step guide invest share market india
1,2,What is the step by step guide to invest in sh...,step step guide invest share market
2,3,What is the story of Kohinoor (Koh-i-Noor) Dia...,story kohinoor diamond
3,4,What would happen if the Indian government sto...,would happen indian government stole kohinoor ...
4,5,How can I increase the speed of my internet co...,increase speed internet connection using vpn

In [5]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def clean_query(text):
    text = text.lower()  # تصغير الحروف
    text = re.sub(r'[^a-z\s]', '', text)  # حذف الرموز والأرقام
    words = word_tokenize(text)  # تقسيم الكلمات
    words = [w for w in words if w not in stop_words]  # حذف stopwords
    return " ".join(words)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\RTD\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\RTD\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [8]:
query = "What is the step by step guide to invest in share market?"
cleaned_query = clean_query(query)

print(cleaned_query)

step step guide invest share market

In [9]:
import nltk
from nltk.corpus import wordnet
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\RTD\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [11]:
def refine_query(query):
    cleaned = clean_query(query)
    words = cleaned.split()
    
    expanded_query = set(words)
    
    for w in words:
        expanded_query.update(get_synonyms(w))
    
    return " ".join(expanded_query)

In [12]:
query = "internet speed vpn"
print(refine_query(query))

NameError: name 'get_synonyms' is not defined

In [13]:
import nltk
from nltk.corpus import wordnet

nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\RTD\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [14]:
query = "internet speed vpn"
print(refine_query(query))

NameError: name 'get_synonyms' is not defined

In [15]:
from nltk.corpus import wordnet

In [16]:
def get_synonyms(word):
    synonyms = set()
    
    for syn in wordnet.synsets(word):
        for lemma in syn.lemmas():
            synonym = lemma.name().replace("_", " ")
            synonyms.add(synonym.lower())
    
    return list(synonyms)

In [17]:
print(get_synonyms("internet"))

['net', 'cyberspace', 'internet']

In [18]:
import pandas as pd
from collections import Counter

df = pd.read_csv("quora_cleaned_sample.csv")

all_text = " ".join(df["cleaned_text"].astype(str))
vocab = all_text.split()

word_freq = Counter(vocab)

FileNotFoundError: [Errno 2] No such file or directory: 'quora_cleaned_sample.csv'

In [19]:
import pandas as pd

df = pd.read_csv(r"C:\quora_cleaned_sample.csv")

In [20]:
import pandas as pd
from collections import Counter
import re

In [21]:
df = pd.read_csv(r"C:\quora_cleaned_sample.csv")

In [22]:
all_text = " ".join(df["cleaned_text"].astype(str))
words = all_text.split()

word_freq = Counter(words)

In [23]:
def suggest_words(partial, top_n=5):
    suggestions = []
    
    for word in word_freq:
        if word.startswith(partial):
            suggestions.append(word)
    
    suggestions = sorted(suggestions, key=lambda x: word_freq[x], reverse=True)
    
    return suggestions[:top_n]

In [24]:
def suggest_query(query):
    query = query.lower()
    query = re.sub(r'[^a-z\s]', '', query)
    
    words = query.split()
    
    result = []
    
    for w in words:
        suggestions = suggest_words(w)
        
        if suggestions:
            result.append(suggestions[0])
        else:
            result.append(w)
    
    return " ".join(result)

In [25]:
query = "intenet spedd vpn"

print("Original:", query)
print("Suggested:", suggest_query(query))

Original: intenet spedd vpn
Suggested: intenet spedd vpn

In [26]:
import pandas as pd

df = pd.read_csv(r"C:\quora_cleaned_sample.csv")  # عدلي المسار إذا مختلف

print(df.shape)
df.head()

(10001, 3)

,doc_id,original_text,cleaned_text
0,1,What is the step by step guide to invest in sh...,step step guide invest share market india
1,2,What is the step by step guide to invest in sh...,step step guide invest share market
2,3,What is the story of Kohinoor (Koh-i-Noor) Dia...,story kohinoor diamond
3,4,What would happen if the Indian government sto...,would happen indian government stole kohinoor ...
4,5,How can I increase the speed of my internet co...,increase speed internet connection using vpn

In [27]:
import nltk
from nltk.corpus import stopwords, wordnet
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words("english"))

def get_synonyms(word):
    synonyms = set()
    for syn in wordnet.synsets(word):
        for lemma in syn.lemmas():
            synonyms.add(lemma.name().replace("_", " "))
    return list(synonyms)

def clean_query(query):
    tokens = word_tokenize(query.lower())
    return [w for w in tokens if w.isalnum() and w not in stop_words]

def process_query(query, expand=True):
    words = clean_query(query)

    if not expand:
        return " ".join(words)

    expanded = set(words)

    for w in words:
        expanded.update(get_synonyms(w))

    return " ".join(expanded)

# TEST
query = "internet speed vpn"

print("Original:", query)
print("Processed:", process_query(query))

Original: internet speed vpn
Processed: speed travel rapidly internet upper pelt along net hurry accelerate race hurrying bucket along focal ratio fastness amphetamine hotfoot velocity pep pill f number speed up belt along cannonball along swiftness rush step on it zip hie stop number cyberspace quicken vpn speeding hasten rush along

In [28]:
import nltk
from nltk.corpus import stopwords, wordnet
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words("english"))

# -------------------------
# Clean Query
# -------------------------
def clean_query(query):
    tokens = word_tokenize(query.lower())
    return [w for w in tokens if w.isalnum() and w not in stop_words]

# -------------------------
# Synonyms (FILTERED)
# -------------------------
def get_synonyms(word, limit=3):
    synonyms = set()

    for syn in wordnet.synsets(word):
        for lemma in syn.lemmas():
            w = lemma.name().replace("_", " ")

            # فلترة: نأخذ كلمات قصيرة فقط ومفيدة
            if w.isalpha() and len(w) < 15:
                synonyms.add(w)

            if len(synonyms) >= limit:
                break

        if len(synonyms) >= limit:
            break

    return list(synonyms)

# -------------------------
# Main Query Processing
# -------------------------
def process_query(query, expand=True):
    words = clean_query(query)

    if not expand:
        return " ".join(words)

    expanded = set(words)

    for w in words:
        expanded.update(get_synonyms(w))

    return " ".join(expanded)

# -------------------------
# TEST
# -------------------------
query = "internet speed vpn"

print("Original:", query)
print("Processed:", process_query(query))

Original: internet speed vpn
Processed: net velocity speed cyberspace internet vpn swiftness